# Nesta atividade, com o uso do módulo math, veremos como descobrir o seno, cosseno e tangente de um ângulo que foi inserido.
from math import radians, sin, cos, tan
print('**'*40)
print('Digite um ângulo e descubra qual é seu Seno, seu Cosseno e sua Tangente! ')
print('**'*40)
a = int(input('Escolha um ângulo: '))
s = sin(radians(a))
c = cos(radians(a))
t = tan(radians(a))
print(f'O ângulo escolhido foi {a}°')
print('-')
print(f'O Seno deste é {s:.2f}')
print('-')
print(f'O Cosseno deste ângulo é {c:.2f}')
print('-')
print(f'E a Tangente deste ângulo é {t:.2f}')
